#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import print_function

import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.abspath(os.path.join(HERE, "..", ".."))
if BASE not in sys.path:
    sys.path.insert(0, BASE)

from modules.inventory import planner_v10 as v10
from modules.inventory import planner_v9 as v9
from modules.inventory import planner_v9_core as core

PLANNER_VERSION = "5.3-product"
ORIG_BUILD_PLAN = v10.build_plan


def _recover_existing_collision_devices(plan, state):
    """Recover already matched collision-safe Devices that legacy reconciliation blocked.

    This is deliberately narrower than the original post-create recovery: the row
    must already point to one existing Device and serial + every discovered IP +
    role + Device Type must all confirm that same object. The existing NetBox name
    must also carry the serial suffix generated by the product.
    """
    devices = dict(
        (item.get("id"), item)
        for item in (state.get("devices") or [])
        if item.get("id") is not None
    )

    for row in plan or []:
        device_id = row.get("existing_device_id")
        if not device_id:
            continue
        if v10.clean(row.get("decision")) != "BLOCKED":
            continue
        reasons = set(v10.clean(reason) for reason in (row.get("reasons") or []))
        if "DUPLICATE_DESIRED_NAME" not in reasons:
            continue

        device = devices.get(device_id) or {}
        if not device:
            continue
        serial = v10.identity.norm_serial(row.get("serial"))
        live_serial = v10.identity.norm_serial(device.get("serial"))
        if not serial or live_serial != serial:
            continue
        if v10.clean(device.get("description")) != v10.PRODUCT_DEVICE_DESCRIPTION:
            continue

        suffix = serial[-6:] if len(serial) >= 6 else serial
        live_name = v10.clean(device.get("name"))
        if not suffix or not live_name.upper().endswith("-" + suffix.upper()):
            continue
        if not v10._device_matches_row(device, row, state):
            continue

        row["suppressed_reasons"] = list(row.get("reasons") or [])
        row["desired_name"] = live_name
        row["effective_name"] = live_name
        row["name_authority"] = "NETBOX_EXISTING"
        row["name_write_allowed"] = False
        row["decision"] = "READY"
        row["action"] = "NOOP"
        row["safe_diffs"] = []
        row["match_state"] = "MATCHED"
        row["match_reason"] = "Serial/IP confirmam Device de colisão já existente"
        row["reasons"] = ["EXISTING_COLLISION_IDENTITY_MATCHED"]
        row["identity_policy"] = "COLLISION_SAFE_EXISTING_MATCH"
        for intent in row.get("ip_intents") or []:
            intent["action"] = "NOOP"


def _enforce_stable_identity_for_new_creates(plan):
    """Fail closed for every new Device candidate whose final identity is weak.

    Earlier role-specific guards covered physical Devices and known Windows roles,
    but a generic WINDOWS_HOST or HOST_OR_APPLIANCE row could still finish as
    READY/CREATE with a WEAK discovery UID. The final Planner layer is the last
    authority before the write guard, so it must reject every new weak identity
    regardless of role or asset class.
    """
    for row in plan or []:
        if row.get("existing_device_id"):
            continue
        if v10.clean(row.get("decision")) != "READY":
            continue
        if v10.clean(row.get("action")) != "CREATE":
            continue
        uid = v10.clean(row.get("discovery_uid")).upper()
        if not uid.startswith("WEAK:"):
            continue

        row["decision"] = "REVIEW"
        row["action"] = "NOOP"
        row["interfaces"] = []
        row["ip_intents"] = []
        row["safe_diffs"] = []
        row.pop("repair", None)
        reasons = list(row.get("reasons") or [])
        marker = "NEW_DEVICE_REQUIRES_STABLE_IDENTITY"
        if marker not in reasons:
            reasons.append(marker)
        row["reasons"] = sorted(set(reasons))
        row["identity_policy"] = "FINAL_NEW_CREATE_IDENTITY_NOT_STABLE"


def _limit(name, default):
    raw = v10.clean(os.environ.get(name))
    if not raw:
        return default
    try:
        return max(0, int(raw))
    except ValueError:
        return default


def _apply_final_write_guard(plan, state):
    """Apply absolute limits always and percentage only after a stable site baseline.

    A site with few Devices is commonly being onboarded. Applying a percentage to
    a base of 13 Devices, for example, makes 17 otherwise eligible additions look
    like 131% growth and prevents any controlled bootstrap. For bases below the
    configured minimum, absolute CREATE/UPDATE/REPAIR/TOTAL caps remain mandatory;
    only the percentage rule is deferred until the site has enough live Devices.
    """
    limits = {
        "CREATE": _limit("NETBOX_DISCOVERY_MAX_CREATE", 25),
        "UPDATE_SAFE": _limit("NETBOX_DISCOVERY_MAX_UPDATE", 50),
        "REPAIR_SAFE_VM_DUPLICATE": _limit("NETBOX_DISCOVERY_MAX_REPAIR", 20),
        "TOTAL": _limit("NETBOX_DISCOVERY_MAX_TOTAL_CHANGES", 75),
        "PERCENT": _limit("NETBOX_DISCOVERY_MAX_CHANGE_PERCENT", 20),
        "PERCENT_MIN_BASE": _limit("NETBOX_DISCOVERY_PERCENT_MIN_BASE", 50),
    }
    eligible = [
        row for row in plan
        if v10.clean(row.get("decision")) == "READY"
        and v10.clean(row.get("action")) in (
            "CREATE", "UPDATE_SAFE", "REPAIR_SAFE_VM_DUPLICATE"
        )
    ]
    counts = Counter(v10.clean(row.get("action")) for row in eligible)
    live_count = len(state.get("devices") or [])
    percent_denominator = max(1, live_count)
    percent = int(round((100.0 * len(eligible)) / percent_denominator))
    percent_enforced = live_count >= limits["PERCENT_MIN_BASE"]

    violations = []
    for action in ("CREATE", "UPDATE_SAFE", "REPAIR_SAFE_VM_DUPLICATE"):
        if counts.get(action, 0) > limits[action]:
            violations.append("{0}={1}>{2}".format(action, counts[action], limits[action]))
    if len(eligible) > limits["TOTAL"]:
        violations.append("TOTAL={0}>{1}".format(len(eligible), limits["TOTAL"]))
    if percent_enforced and percent > limits["PERCENT"] and len(eligible) > 10:
        violations.append("PERCENT={0}%>{1}%".format(percent, limits["PERCENT"]))

    guard = {
        "status": "BLOCK" if violations else "PASS",
        "counts": dict(counts),
        "eligible_total": len(eligible),
        "live_devices": live_count,
        "change_percent": percent,
        "limits": limits,
        "violations": violations,
        "percent_enforced": bool(percent_enforced),
        "percent_min_base": limits["PERCENT_MIN_BASE"],
        "policy": "ABSOLUTE_AND_PERCENT" if percent_enforced else "SMALL_SITE_BOOTSTRAP_ABSOLUTE_ONLY",
    }
    for row in plan:
        row["write_guard"] = guard
    if not violations:
        return

    reason = "WRITE_GUARD_LIMIT_EXCEEDED:{0}".format(",".join(violations))
    for row in eligible:
        row["decision"] = "BLOCKED"
        row["action"] = "NOOP"
        row["reasons"] = [reason]
        row["interfaces"] = []
        row["ip_intents"] = []
        row.pop("repair", None)
        row["identity_policy"] = "GLOBAL_WRITE_GUARD"


def _defer_write_guard(plan, state):
    """Do not mutate intermediate decisions; Planner V11 applies the final guard."""
    return None


def build_plan(recon, classification, state):
    # Planner V9 Core, V9 and V10 all call the same guard while layering policies.
    # Running it in an intermediate layer can turn candidates into BLOCKED before
    # later identity policies correctly downgrade them to REVIEW. Defer every
    # nested invocation and evaluate once, after the complete V11 decision set.
    original_write_guard = core._apply_write_guard
    core._apply_write_guard = _defer_write_guard
    try:
        plan, prereq = ORIG_BUILD_PLAN(recon, classification, state)
    finally:
        core._apply_write_guard = original_write_guard

    _recover_existing_collision_devices(plan, state)
    _enforce_stable_identity_for_new_creates(plan)
    v10._attach_idempotency_identity(plan)
    v9._prune_prerequisites_to_ready_actions(plan, prereq)
    _apply_final_write_guard(plan, state)
    return plan, prereq


def main(argv=None):
    args = list(sys.argv[1:] if argv is None else argv)
    if args and args[0].lower() in ("summary", "blocked", "review", "ready", "delegated", "all"):
        from modules.product import plan_report
        return plan_report.main(args)

    old_build = v10.build_plan
    old_version = v10.PLANNER_VERSION
    try:
        v10.build_plan = build_plan
        v10.PLANNER_VERSION = PLANNER_VERSION
        return v10.main(args)
    finally:
        v10.build_plan = old_build
        v10.PLANNER_VERSION = old_version


if __name__ == "__main__":
    raise SystemExit(main())
