#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import print_function

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.abspath(os.path.join(HERE, "..", ".."))
if BASE not in sys.path:
    sys.path.insert(0, BASE)

from modules.inventory import planner_v10 as v10
from modules.inventory import planner_v9 as v9
from modules.inventory import planner_v9_core as core

PLANNER_VERSION = "5.3-product"
ORIG_BUILD_PLAN = v10.build_plan


def _recover_existing_collision_devices(plan, state):
    """Recover already matched collision-safe Devices that legacy reconciliation blocked.

    This is deliberately narrower than the original post-create recovery: the row
    must already point to one existing Device and serial + every discovered IP +
    role + Device Type must all confirm that same object. The existing NetBox name
    must also carry the serial suffix generated by the product.
    """
    devices = dict(
        (item.get("id"), item)
        for item in (state.get("devices") or [])
        if item.get("id") is not None
    )

    for row in plan or []:
        device_id = row.get("existing_device_id")
        if not device_id:
            continue
        if v10.clean(row.get("decision")) != "BLOCKED":
            continue
        reasons = set(v10.clean(reason) for reason in (row.get("reasons") or []))
        if "DUPLICATE_DESIRED_NAME" not in reasons:
            continue

        device = devices.get(device_id) or {}
        if not device:
            continue
        serial = v10.identity.norm_serial(row.get("serial"))
        live_serial = v10.identity.norm_serial(device.get("serial"))
        if not serial or live_serial != serial:
            continue
        if v10.clean(device.get("description")) != v10.PRODUCT_DEVICE_DESCRIPTION:
            continue

        suffix = serial[-6:] if len(serial) >= 6 else serial
        live_name = v10.clean(device.get("name"))
        if not suffix or not live_name.upper().endswith("-" + suffix.upper()):
            continue
        if not v10._device_matches_row(device, row, state):
            continue

        row["suppressed_reasons"] = list(row.get("reasons") or [])
        row["desired_name"] = live_name
        row["effective_name"] = live_name
        row["name_authority"] = "NETBOX_EXISTING"
        row["name_write_allowed"] = False
        row["decision"] = "READY"
        row["action"] = "NOOP"
        row["safe_diffs"] = []
        row["match_state"] = "MATCHED"
        row["match_reason"] = "Serial/IP confirmam Device de colisão já existente"
        row["reasons"] = ["EXISTING_COLLISION_IDENTITY_MATCHED"]
        row["identity_policy"] = "COLLISION_SAFE_EXISTING_MATCH"
        for intent in row.get("ip_intents") or []:
            intent["action"] = "NOOP"


def build_plan(recon, classification, state):
    plan, prereq = ORIG_BUILD_PLAN(recon, classification, state)
    _recover_existing_collision_devices(plan, state)
    v10._attach_idempotency_identity(plan)
    v9._prune_prerequisites_to_ready_actions(plan, prereq)
    core._apply_write_guard(plan, state)
    return plan, prereq


def main(argv=None):
    old_build = v10.build_plan
    old_version = v10.PLANNER_VERSION
    try:
        v10.build_plan = build_plan
        v10.PLANNER_VERSION = PLANNER_VERSION
        return v10.main(argv)
    finally:
        v10.build_plan = old_build
        v10.PLANNER_VERSION = old_version


if __name__ == "__main__":
    raise SystemExit(main())
